version: '2'

services:
  nginx:
    container_name: sungjin-log-nginx
    build: ./nginx
    links:
      - frontEnd:frontEnd
      - backEnd:backEnd
    ports:
      - 3000:80
    depends_on:
      - frontEnd
      - backEnd

  frontEnd:
    container_name: sungjin-log-front
    image: sungjin-log-front:test
    ports:
      - 3000

  backEnd:
    container_name: sungjin-log-back
    image: sungjin-log-back:test
    ports:
      - 3000