version: '3'

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./docker/data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=sungjinlogtest
  #     - POSTGRES_USER=sungjin
  #     - POSTGRES_PASSWORD=wkdtjdwls1!
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  nextjs:
    ports:
      - 80:80
    build:
      context: ./front
      dockerfile: dockerfile
    volumes:
      - ./front:/usr/src/front
      - /usr/src/front/node_modules
      - /usr/src/front/.next
    env_file:
      - ./front/.env

  backend:
    ports:
      - 4000:4000
    build:
      context: ./back
      dockerfile: dockerfile
    volumes:
      - ./back:/usr/src/back
      - /usr/src/back/node_modules
    env_file:
      - ./back/.env
    